input {
  file {
    path => "/data/wetter.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    index => "wetter-%{+YYYY.MM.dd}"
    user => "admin"
    password => "aPbS80wXr06#MauSi10"
    ssl_certificate_verification => false
  }
}


